# Generated by Django 3.0 on 2022-09-16 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_itemtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('concentration', models.IntegerField(null=True)),
                ('conentration_units', models.CharField(max_length=20, null=True)),
                ('volume', models.IntegerField(null=True)),
                ('volume_units', models.CharField(max_length=20, null=True)),
                ('description', models.TextField(null=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_id', to='api.Category')),
                ('container_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='container_id', to='api.Container')),
                ('exp_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exp_id', to='api.Experiment')),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_type_id', to='api.ItemType')),
                ('manufacturer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer_id', to='api.Manufacturer')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('storage_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_ID', to='api.Storage')),
            ],
        ),
    ]
